name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build-node:
    name: Build Node Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Node Docker Image
        run: docker build -t node-app ./node-app


  build-python:
    name: Build Python Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Python Docker Image
        run: docker build -t python-app ./python-app


  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    needs:
      - build-node
      - build-python

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stack deploy -c ~/devops-assignment/docker-stack.yml multi-client
